FROM postgres:16.1-bullseye

WORKDIR /app

COPY  ../sql /app

# todo 
# install goose and sqlc using go builder container 
# then copy in postgres containers bin folder to execute
# them from an entrypoint


